apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  namespace: stage
  labels:
    app: atlas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
      - name: atlas
        image: nginx:1.20.0  # ← version
        env:
        - name: MIGRATION_ID
          value: "2"         # ← migration_id