# Создание AtlasApp для существующих deployments

# 1. Dev environment (1.21.0, migration 5)
apiVersion: atlas.io/v1
kind: AtlasApp
metadata:
  name: atlas-dev
  namespace: dev
spec:
  environment: dev
  version: "1.21.0"
  migrationId: 5
  replicas: 3
  autoPromote: true
  nextEnvironment: stage
  healthCheckPath: "/"
---
# 2. Stage environment (1.20.0, migration 2)  
apiVersion: atlas.io/v1
kind: AtlasApp
metadata:
  name: atlas-stage
  namespace: stage
spec:
  environment: stage
  version: "1.20.0"
  migrationId: 2
  replicas: 3
  autoPromote: true
  nextEnvironment: prod
  healthCheckPath: "/"
---
# 3. Prod environment (1.18.0, migration 1)
apiVersion: atlas.io/v1
kind: AtlasApp
metadata:
  name: atlas-prod
  namespace: prod
spec:
  environment: prod
  version: "1.18.0"
  migrationId: 1
  replicas: 3
  autoPromote: false
  requireApproval: true
  healthCheckPath: "/"
